insert into curriculum(country, state, description) values('Australia', 'NSW', 'NSW State Language Curriculum');
insert into curriculum(country, state, description) values('Australia','QLD','Queensland English Curriculum');
insert into curriculum(country, state, description) values('Australia','VIC','VIC English Curriculum');
insert into school_type_identifiers(school_type_identifier_name, school_type_identifier_description) values('Primary School', 'Australian Primary School - Level 0 to 6');
insert into school_type_identifiers(school_type_identifier_name, school_type_identifier_description) values('Secondary School', 'Australian Secondary School - Level 7 to 10');
select * from school_type_identifiers;
insert into schools(name, curriculum_details_curriculum_details_Id, school_type_id) values('Hawthorn Primary', 1, 1);
select * from schools;
insert into school_teachers(teachers_user_Id, schools_school_Id) values(1, 1);
select * from school_teachers;
insert into school_types(fk_curriculum_id, fk_school_type_id, type_name) values(1, 1, 'primary');
insert into school_types(fk_curriculum_id, fk_school_type_id, type_name) values(2, 1, 'secondary');
insert into scriibi_levels(scriibi_Level) values (	-5.00	);
insert into scriibi_levels(scriibi_Level) values (	-4.75	);
insert into scriibi_levels(scriibi_Level) values (	-4.50	);
insert into scriibi_levels(scriibi_Level) values (	-4.25	);
insert into scriibi_levels(scriibi_Level) values (	-4.00	);
insert into scriibi_levels(scriibi_Level) values (	-3.75	);
insert into scriibi_levels(scriibi_Level) values (	-3.50	);
insert into scriibi_levels(scriibi_Level) values (	-3.25	);
insert into scriibi_levels(scriibi_Level) values (	-3.00	);
insert into scriibi_levels(scriibi_Level) values (	-2.75	);
insert into scriibi_levels(scriibi_Level) values (	-2.50	);
insert into scriibi_levels(scriibi_Level) values (	-2.25	);
insert into scriibi_levels(scriibi_Level) values (	-2.00	);
insert into scriibi_levels(scriibi_Level) values (	-1.75	);
insert into scriibi_levels(scriibi_Level) values (	-1.50	);
insert into scriibi_levels(scriibi_Level) values (	-1.25	);
insert into scriibi_levels(scriibi_Level) values (	-1.00	);
insert into scriibi_levels(scriibi_Level) values (	-0.75	);
insert into scriibi_levels(scriibi_Level) values (	-0.50	);
insert into scriibi_levels(scriibi_Level) values (	-0.25	);
insert into scriibi_levels(scriibi_Level) values (	0.00	);
insert into scriibi_levels(scriibi_Level) values (	0.25	);
insert into scriibi_levels(scriibi_Level) values (	0.50	);
insert into scriibi_levels(scriibi_Level) values (	0.75	);
insert into scriibi_levels(scriibi_Level) values (	1.00	);
insert into scriibi_levels(scriibi_Level) values (	1.25	);
insert into scriibi_levels(scriibi_Level) values (	1.50	);
insert into scriibi_levels(scriibi_Level) values (	1.75	);
insert into scriibi_levels(scriibi_Level) values (	2.00	);
insert into scriibi_levels(scriibi_Level) values (	2.25	);
insert into scriibi_levels(scriibi_Level) values (	2.50	);
insert into scriibi_levels(scriibi_Level) values (	2.75	);
insert into scriibi_levels(scriibi_Level) values (	3.00	);
insert into scriibi_levels(scriibi_Level) values (	3.25	);
insert into scriibi_levels(scriibi_Level) values (	3.50	);
insert into scriibi_levels(scriibi_Level) values (	3.75	);
insert into scriibi_levels(scriibi_Level) values (	4.00	);
insert into scriibi_levels(scriibi_Level) values (	4.25	);
insert into scriibi_levels(scriibi_Level) values (	4.50	);
insert into scriibi_levels(scriibi_Level) values (	4.75	);
insert into scriibi_levels(scriibi_Level) values (	5.00	);
insert into scriibi_levels(scriibi_Level) values (	5.25	);
insert into scriibi_levels(scriibi_Level) values (	5.50	);
insert into scriibi_levels(scriibi_Level) values (	5.75	);
insert into scriibi_levels(scriibi_Level) values (	6.00	);
insert into scriibi_levels(scriibi_Level) values (	6.25	);
insert into scriibi_levels(scriibi_Level) values (	6.50	);
insert into scriibi_levels(scriibi_Level) values (	6.75	);
insert into scriibi_levels(scriibi_Level) values (	7.00	);
insert into scriibi_levels(scriibi_Level) values (	7.25	);
insert into scriibi_levels(scriibi_Level) values (	7.50	);
insert into scriibi_levels(scriibi_Level) values (	7.75	);
insert into scriibi_levels(scriibi_Level) values (	8.00	);
insert into scriibi_levels(scriibi_Level) values (	8.25	);
insert into scriibi_levels(scriibi_Level) values (	8.50	);
insert into scriibi_levels(scriibi_Level) values (	8.75	);
insert into scriibi_levels(scriibi_Level) values (	9.00	);
insert into scriibi_levels(scriibi_Level) values (	9.25	);
insert into scriibi_levels(scriibi_Level) values (	9.50	);
insert into scriibi_levels(scriibi_Level) values (	9.75	);
insert into scriibi_levels(scriibi_Level) values (	10.00	);
insert into scriibi_levels(scriibi_Level) values (	10.25	);
insert into scriibi_levels(scriibi_Level) values (	10.50	);
insert into scriibi_levels(scriibi_Level) values (	10.75	);
insert into scriibi_levels(scriibi_Level) values (	11.00	);
insert into scriibi_levels(scriibi_Level) values (	11.25	);
insert into scriibi_levels(scriibi_Level) values (	11.50	);
insert into scriibi_levels(scriibi_Level) values (	11.75	);
insert into scriibi_levels(scriibi_Level) values (	12.00	);
insert into scriibi_levels(scriibi_Level) values (	12.25	);
insert into scriibi_levels(scriibi_Level) values (	12.50	);
insert into scriibi_levels(scriibi_Level) values (	12.75	);
insert into scriibi_levels(scriibi_Level) values (	13.00	);
insert into scriibi_levels(scriibi_Level) values (	13.25	);
insert into scriibi_levels(scriibi_Level) values (	13.50	);
insert into scriibi_levels(scriibi_Level) values (	13.75	);
insert into scriibi_levels(scriibi_Level) values (	14.00	);
insert into grade_labels(fk_school_type_id, fk_scriibi_level_id, grade_label) values(1, 125, 'grade 1');
insert into grade_labels(fk_school_type_id, fk_scriibi_level_id, grade_label) values(1, 129, 'grade 2');
insert into grade_labels(fk_school_type_id, fk_scriibi_level_id, grade_label) values(1, 133, 'grade 3');
insert into grade_labels(fk_school_type_id, fk_scriibi_level_id, grade_label) values(1, 137, 'grade 4');
insert into grade_labels(fk_school_type_id, fk_scriibi_level_id, grade_label) values(1, 141, 'grade 5');
insert into grade_labels(fk_school_type_id, fk_scriibi_level_id, grade_label) values(1, 145, 'grade 6');
insert into grade_labels(fk_school_type_id, fk_scriibi_level_id, grade_label) values(1, 149, 'grade 7');
insert into grade_labels(fk_school_type_id, fk_scriibi_level_id, grade_label) values(1, 153, 'grade 8');
select * from grade_labels;
insert into assessed_level_labels(school_type_id_fk, school_scriibi_level_id, assessed_level_label) values(1, 125, 'assessment level 1');
insert into assessed_level_labels(school_type_id_fk, school_scriibi_level_id, assessed_level_label) values(1, 129, 'assessment level 2');
insert into assessed_level_labels(school_type_id_fk, school_scriibi_level_id, assessed_level_label) values(1, 133, 'assessment level 3');
insert into assessed_level_labels(school_type_id_fk, school_scriibi_level_id, assessed_level_label) values(1, 137, 'assessment level 4');
insert into assessed_level_labels(school_type_id_fk, school_scriibi_level_id, assessed_level_label) values(1, 141, 'assessment level 5');
select * from assessed_level_labels;
insert into classes(class_Name, schools_school_Id) values('English class', 1);
insert into classes(class_Name, schools_school_Id) values('History class', 1);
insert into classes(class_Name, schools_school_Id) values('French class', 1);
select * from classes;
insert into classes_teachers(classes_teachers_classes_class_Id, teachers_user_Id) values(1, 1);
/**insert into classes_teachers(classes_teachers_classes_class_Id, teachers_user_Id) values(2, 2);**/
select * from classes_teachers;
insert into students(student_First_Name, student_Last_Name, Student_Gov_Id, enrolled_Level_Id, rubrik_level, schools_school_Id) values('Edith', 'Richardson', '0h6bsj15g2', 1, 2, 1);
insert into students(student_First_Name, student_Last_Name, Student_Gov_Id, enrolled_Level_Id, rubrik_level, schools_school_Id) values('Chelsea', 'Chapman', 'ftsyph208i', 3, 1, 1);
insert into students(student_First_Name, student_Last_Name, Student_Gov_Id, enrolled_Level_Id, rubrik_level, schools_school_Id) values('Justin', 'Hill', 'jf6gdg8oaa', 2, 1, 1);
insert into students(student_First_Name, student_Last_Name, Student_Gov_Id, enrolled_Level_Id, rubrik_level, schools_school_Id) values('Penelope', 'Johnson', 'bhg8uv3gwx', 1, 2, 1);
insert into students(student_First_Name, student_Last_Name, Student_Gov_Id, enrolled_Level_Id, rubrik_level, schools_school_Id) values('Alina', 'Ellis', 'rk4p0vu0d4', 3, 1, 1);
insert into students(student_First_Name, student_Last_Name, Student_Gov_Id, enrolled_Level_Id, rubrik_level, schools_school_Id) values('Julia', 'Watson', 'f972obzfjn', 3, 1, 1);
select * from students;
insert into classes_students(classes_class_Id, students_student_Id, student_grade_label_id, student_assessed_label_id) values(1,1, 1, 2);
insert into classes_students(classes_class_Id, students_student_Id, student_grade_label_id, student_assessed_label_id) values(1,2, 3, 1);
insert into classes_students(classes_class_Id, students_student_Id, student_grade_label_id, student_assessed_label_id) values(1,3, 2, 1);
insert into classes_students(classes_class_Id, students_student_Id, student_grade_label_id, student_assessed_label_id) values(1,4, 1, 2);
insert into classes_students(classes_class_Id, students_student_Id, student_grade_label_id, student_assessed_label_id) values(1,5, 3, 1);
insert into classes_students(classes_class_Id, students_student_Id, student_grade_label_id, student_assessed_label_id) values(1,6, 3, 1);
select * from classes_students;
insert into positions(position_Name) values ('literacy lead');
insert into positions(position_Name) values ('principal');
insert into positions(position_Name) values ('gradelevel');
insert into traits(trait_Name, colour, icon) values ('Ideas', 'yellow', '/trait-con/ideas.png');
insert into traits(trait_Name, colour, icon) values ('Organisation', 'red', '/trait-con/organisation.png');
insert into traits(trait_Name, colour, icon) values ('Word Choice', 'green', '/trait-con/wordchoice.png');
insert into traits(trait_Name, colour, icon) values ('Conventions', 'pink', '/trait-con/conventions.png');
insert into traits(trait_Name, colour, icon) values ('Sentence Fluency', 'blue', '/trait-con/sentencefluency.png');
insert into traits(trait_Name, colour, icon) values ('Voice', 'grey', '/trait-con/voice.png');
insert into traits(trait_Name, colour, icon) values ('Other Skills', 'purple', '/trait-con/otherskills.png');
select * from traits;
insert into skills(skill_Name, skill_def) values ('	Opening / Introduction'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Character Development'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Cohesion'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Comparing Texts'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Concepts about Print'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Connectives	', 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Creating Texts'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Developing Ideas'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Sentence Type and Structure	', 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Elaborating on Ideas'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Ending / Conclusion'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Figurative Language'	, '	Description'	);
insert into skills(skill_Name, skill_def) values ('	Finding Ideas'	, '	Description'	);
insert into skills(skill_Name, skill_def) values ('	Grammar Usage'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Handwriting / Mark Making'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Language Features and Text Structures'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Modality'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Narrowing Ideas'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Language for Written Texts'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Pacing'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Paragraphing'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Precise Language'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Punctuation'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Purpose and Audience'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Retell / Summarising'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Revision and Editing'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Sentence Beginnings'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Sentence Flow and Fluency'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Sentence Length'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Sequencing'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Software / Digital Media (Multimodal)'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Spelling'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Text Patterns'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Vocabulary'	, 	'Description'	);
insert into skills(skill_Name, skill_def) values ('	Writer’s Voice (Tone)'	, 	'Description'	);

insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	2,		11	);
insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	2,		30	);
insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	3,		12	);
insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	1,		13	);
insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	4,		26	);
insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	6,		2	);
insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	2,		1	);
insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	3,		19	);
insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	3,		17	);
insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	4,		15	);
insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	7,		5	);
insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	7,		4	);
insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	1,		18	);
insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	2,		21	);
insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	1,		8	);
insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	1,		10	);
insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	5,		29	);
insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	2,		20	);
insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	4,		23	);
insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	2,		6	);
insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	7,		3	);
insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	7,		7	);
insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	5,		27	);
insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	4,		14	);
insert into skills_traits(skills_traits_traits_trait_Id, skills_traits_skills_skill_Id) values (	4,		33	);

insert into text_types(text_type_Name, text_type_Desc) values('Narrative', "This is a decrription for a Narrative text type");
insert into text_types(text_type_Name, text_type_Desc) values('Recount', "This is a decrription for a Recount text type");
insert into text_types(text_type_Name, text_type_Desc) values('Information Report', "This is a decrription for a Information Report text type");
insert into text_types(text_type_Name, text_type_Desc) values('Persuasive', "This is a decrription for a Persuasive text type");
insert into text_types(text_type_Name, text_type_Desc) values('Explanation', "This is a decrription for a Explanation text type");
insert into text_types(text_type_Name, text_type_Desc) values('Procedural', "This is a decrription for a Procedural text type");
insert into text_types(text_type_Name, text_type_Desc) values('Description', "This is a decrription for a Description text type");
insert into text_types(text_type_Name, text_type_Desc) values('Transactional', "This is a decrription for a Transactional text type");
insert into text_types(text_type_Name, text_type_Desc) values('Discussion', "This is a decrription for a Discussion text type");
insert into text_types(text_type_Name, text_type_Desc) values('Personal Response', "This is a decrription for a Personal Response text type");
insert into text_types(text_type_Name, text_type_Desc) values('Poetry', "This is a decrription for a Poetry text type");
insert into teaching_periods (period_Name) values('undefined');


insert into global_criterias(description) values ('Can organise texts using paragraphs when the topic, speaker, time or location changes. For information texts, organises longer texts with topic sentences, elaborations and some closing sentences.');
insert into global_criterias(description) values ('	Can retell a familiar text or event by sequencing two to three images and simple statements.');
insert into global_criterias(description) values ('	Can retell a familiar text or event by sequencing two to three images and simple statements.');
insert into global_criterias(description) values ('	Can review own text and make changes during shared editing. Can use delete and Caps Lock function and check their name and font sizes.');
insert into global_criterias(description) values ('	Understands that letters can be represented as written text.  Copies letters and numbers with some control.  Can hold a pencil using a tripod grip.');
insert into global_criterias(description) values ('	Can verbally add additional information about a topic when prompted.');
insert into global_criterias(description) values ('	Can copy own name and recognise some letters within it.  Understands that a full stop represents a pause.');
insert into global_criterias(description) values ('	Use software or application (app) to match images and simple sentences.  For example, matches a picture of a cat with the word cat.');
insert into global_criterias(description) values ('	Can identify the onset of familiar words and some words that have the same rime. Can identify objects that start with the same letter as their name.');
insert into global_criterias(description) values ('	Ties up events with a predictable or simple closing sentence (They lived happily every after, The end, It was fun).	');
insert into global_criterias(description) values ('	Can draw or write three or more simple sentences, to sequence a familiar story or personal experience, based on time and steps.');
insert into global_criterias(description) values ('	Participates in shared editing for own text for meaning, spelling, capital letters and full stops.');
insert into global_criterias(description) values ('	Can draw a character, real or imagined, with close up details that show emotion and action. For example, a girl smiling on a swing.');
insert into global_criterias(description) values ('	The introductory sentence reveals the texts'' purpose or topic. For example, "On the weekend", "I went to a birthday party."');
insert into global_criterias(description) values ('	Understands how written texts are unlike everyday spoken language.  Can explain some rules for written texts, such as spaces between words, writing left to right and correct spelling.');
insert into global_criterias(description) values ('	Understands that sounds are represented by upper and lower-case written letters. Can use correct posture and pencil grip. Writes letters with correct formation after a clear demonstration. Writes words using lower-case letters. Learning to construct some upper-case letters.');
insert into global_criterias(description) values ('	Understands that words convey a message and every book has a front, back, title and author. Understands features of print text, for example directionality, return sweep and spaces between words.');
insert into global_criterias(description) values ('	The topic is defined with either a title or a topic sentence.  However, the writer jumps from one idea to the next.');
insert into global_criterias(description) values ('	Can write additional information about a topic.');
insert into global_criterias(description) values ('	Understands that punctuation is different from letters and can point out capitals and full stops.  Knows that capitals and full stops signal the beginning and end of a sentence.');
insert into global_criterias(description) values ('	Can create short texts to explore, record and report ideas and events using some content familiar words and beginning writing knowledge (writing from left to right, top to bottom).');
insert into global_criterias(description) values ('	Beginning to recognise the stem of a word and can add suffixes "ing", "s", "ed". For example, will add "s" on the word "dog" to show more than one.   Word order is mostly correct, but often only writes root words (They live happy every after).');
insert into global_criterias(description) values ('	Construct texts using software including word processing programs  Can use simple functions of keyboard and mouse including typing letters, scrolling, selecting icons and drop-down menu.');
insert into global_criterias(description) values ('	Retell familiar literary texts through performance, use of illustrations and images.');
insert into global_criterias(description) values ('	Discusses new vocabulary found in texts. Builds vocabulary by discussing everyday experiences, personal interests and topics taught at school.');
insert into global_criterias(description) values ('	Understands that word order in sentences is important for meaning (for example, "The dog sat on the mat", rather than, "The mat sat on the dog".');
insert into global_criterias(description) values ('	Can accurately write consonant-vowel-consonant words. Writes a small range of high frequency and familiar words (fish, they). Building word families using onset and rime (sh/op, st/op).');
insert into global_criterias(description) values ('	Resolves writing with a closing sentence that links to events in the text,  leaving the reader satisfied. (I hope we go back next year).');
insert into global_criterias(description) values ('	Events are written in order with a clear beginning, middle and end.  There is little to no evidence of sequencing ideas using connectives.');
insert into global_criterias(description) values ('	Can create a simile for a card or similar text type, but does not use similes in longer texts (narratives, recounts).');
insert into global_criterias(description) values ('	Can find ideas for imaginative and informative texts with support using graphic organisers.');
insert into global_criterias(description) values ('	Rereads own text and can make some changes to improve meaning (adding adjective to noun), spelling and punctuation.');
insert into global_criterias(description) values ('	Can describe characters'' physical appearance using adjectives and nouns (red dress). Experimenting using dialogue.');
insert into global_criterias(description) values ('	The introductory sentence reveals the texts'' purpose or topic. They include some setting details (where and when). "I live next door to a haunted house."');
insert into global_criterias(description) values ('	Writes legible words using unjoined upper and lower case letters (may use incorrect case - plaYed). Script is of a reasonably consistent size. Is learning correct formation and directionality using correct posture and pencil grip.');
insert into global_criterias(description) values ('	The topic is well defined.  The writer stays on topic but includes irrelevant off-topic information or details.');
insert into global_criterias(description) values ('	Writes multiple ideas, with some supporting details.');
insert into global_criterias(description) values ('	All ideas are given equal importance and the writer does not elaborate on any one particular idea.');
insert into global_criterias(description) values ('	Sentences are of similar length.');
insert into global_criterias(description) values ('	Understands the purpose of full stops, question marks, and exclamation marks.  Most sentences have a capital letter and full stop.  Can write a question and statement using appropriate punctuation.');
insert into global_criterias(description) values ('	Uses connectives to link clauses (and), and sequence events (then).');
insert into global_criterias(description) values ('	Can create short imaginative and informative texts showing an understanding of basic text structures and features (beginning, middle, end, title, headings).');
insert into global_criterias(description) values ('	Applies grammar rules to texts.  Can build word families from common morphemes by recognising the stem in words "walk/ed".  For example, "play", "plays", "played", "playground".');
insert into global_criterias(description) values ('	Can order events chronologically (by time).  For example, 'I woke up early and then went to school'.  Can sequence procedural texts (First, then).');
insert into global_criterias(description) values ('	Is introduced to differences in words to represent people, places and things, verbs, adjectives and adverbs.  Can (with support) replace a common noun and verb with a specific one.  For example, instead of the noun "drink" will write "tea".');
insert into global_criterias(description) values ('	Compose a story or information sequence that incorporates supporting images and captions using software including word processing programs.');
insert into global_criterias(description) values ('	Can retell and recreate simple texts imaginatively using drawing, writing, performance and digital forms of communication.  Includes plot details, characters, setting, conflicts and resolutions.  Uses similar vocabulary in known texts.');
insert into global_criterias(description) values ('	Appropriate vocabulary matches audience and purpose ("Dear" Mr Jones).  Key/topic words represent ideas and clearly convey the  intended message (The volcano erupted).  Experimenting with sensory descriptive words.');
insert into global_criterias(description) values ('	Can write a grammatically correct simple sentence with correct punctuation. Can identify different parts of a simple sentence that represent what is happening and who or what is involved.');
insert into global_criterias(description) values ('	Can match familiar texts with an audience.  For example, knows that an ABC book is written for young children.');
insert into global_criterias(description) values ('	Writes a large range of familiar and high frequency words.  Can spell one and two syllable words with common letter patters. Can write words with long and short vowels ("hat", "hate").');
insert into global_criterias(description) values ('	For narrative, has a clear and predictable resolution for plot and character conflicts. For persuasive, concludes with a common phrase (In conclusion, So,) and restates the main argument.');
insert into global_criterias(description) values ('	Writing is organised with a clear beginning, middle and end. Can write four or more sequenced events or ideas using connectives.');
insert into global_criterias(description) values ('	Can use common similes to describe people, places or things. Is experimenting with original similes, hyperbole and onomatopoeia.');
insert into global_criterias(description) values ('	Independently finds original ideas from a range of sources  (visual prompts, personal experience,  observations) to create imaginative texts.');
insert into global_criterias(description) values ('	Rereads text and responds to teacher and peer feedback to edit text for spelling, sentence-boundary punctuation and text structure (precise nouns for information text) to  improve text.');
insert into global_criterias(description) values ('	Can describe some physical attributes of characters and depict their actions and thought processes in narratives using adjectives, verbs and dialogue.');
insert into global_criterias(description) values ('	Writes a simple orientation with character (who) and setting details (where and when). May experiment with hooks to engage the reader. Persuasive texts: begins with a hook and a statement thesis.');
insert into global_criterias(description) values ('	Writes words and sentences legibly using unjoined upper- and lower-case letters that are applied with growing fluency using an appropriate pen/pencil grip and body position.  Print script is of consistent size.');
insert into global_criterias(description) values ('	Understand that different types of texts have identifiable text structures and language features that help the text serve its purpose. Students can identify the topic and type of text based on it''s visual presentation.');
insert into global_criterias(description) values ('	The topic is broad, but the writer generally stays on topic.');
insert into global_criterias(description) values ('	Attempts to organise work by separating ideas.  Understands that paragraphs are a key organisational feature.');
insert into global_criterias(description) values ('	Writes relevant details to support ideas with text.');
insert into global_criterias(description) values ('	With support, identifies important ideas within a text and can add detail using adjectives and/or the five senses.	');
insert into global_criterias(description) values ('	There is some variation in sentence length through correct placement of full stops and/or dialogue.	');
insert into global_criterias(description) values ('	Some evidence of pacing. The writer has included more detail in the main body of a text.  For example: In a narrative, the orientation and ending are of similar length, and the middle is considerably longer.	');
insert into global_criterias(description) values ('	Can use boundary punctuation (Capitals/full stops). Some proper nouns are capitalised (names, title). Intentionally uses punctuation (?!,"")	');
insert into global_criterias(description) values ('	Uses common connectives to signal a shift in time (later), sequence (next, after that) and add information (and, so).	');
insert into global_criterias(description) values ('	Can make parts of a text more cohesive using devices such as pronouns and connectives.'	);
insert into global_criterias(description) values ('	Can create short imaginative, informative and persuasive texts using growing knowledge of text structures and language features	');
insert into global_criterias(description) values ('	Some variation in sentences beginnings including proper nouns, pronouns, prepositional phrases (On, At), time and sequence transitions (Later, Then), subordinating conjunctions (While, After, Because).	');
insert into global_criterias(description) values ('	Understands that nouns represent people, places, concrete objects and abstract concepts (ideas).  Can expand noun groups/phrases using articles (a, an, the) and adjectives. For example, "I ate a big red apple".	');
insert into global_criterias(description) values ('	Understands and uses some precise words to represent people, places and things, verbs, adjectives and adverbs.  At this stage the writer uses precise words to create strong mental images, rather than avoid wordiness.	');
insert into global_criterias(description) values ('	Creating events, reconstructions of stories or poetry using different media which may include PowerPoint, Apps, word processing programs.	');
insert into global_criterias(description) values ('	Can create written summaries of familiar texts, including narrative plot summaries with basic information on setting, characters, conflicts and resolutions. May need a scaffold (e.g. story map) for support.	');
insert into global_criterias(description) values ('	Conscious choices of vocabulary suit the audience and purpose. Uses some ambitious content words.  Modifying words ('very' excited) and common expressions ("I guess I''ll try harder next time") enhance meaning.');
insert into global_criterias(description) values ('	Can create a compound sentence by connecting simple sentences or independent clauses with conjunctions  (and, but, so, because).  For example, "I went to the beach and I got sunburn".	');
insert into global_criterias(description) values ('	Can identify the audience and purpose of a text and explain their reasoning based on text structure and language features.');
insert into global_criterias(description) values ('	Uses some features of text organisation, including headings, subheadings, basic beginning, middle and end narrative structure.');
insert into global_criterias(description) values ('	Some attempts to engage readers through devices like: rhetorical questions, inverted commas, exclamation marks to add emphasis.');
insert into global_criterias(description) values ('	Uses digraphs, blends, long vowels, silent letters, syllabification to spell simple and compound words. Can spell most high-frequency words accurately and some words that cannot be sounded out (phone).');
insert into global_criterias(description) values ('	For imaginative texts, experiments with different endings (dialogue, humour, profound thought). For persuasive, introduces a concluding paragraph (In conclusion, To sum up), restates the main argument and summarises key points.');
insert into global_criterias(description) values ('	Information is sequenced logically and effectively, enhancing understanding and readability. Sentences are sequenced to reflect a logical and smooth flow of ideas.	');
insert into global_criterias(description) values ('	Uses a variety of figurative language for effect (similes, metaphors, hyperbole, alliteration, personification).');
insert into global_criterias(description) values ('	Independently finds interesting ideas from a range of sources  (visual prompts, personal experience, observations, texts) to create a range of different literary texts.');
insert into global_criterias(description) values ('	Revises (drafts) text to improve ideas, meaning and text structure for audience and purpose. Self and peer edits texts for spelling, grammatical choices and punctuation.');
insert into global_criterias(description) values ('	Characters personality and/or physical traits are revealed throughout the text. ("Mia was 10 years old.  She was nervous about starting at a new school.").	');
insert into global_criterias(description) values ('	Narrative: Attempts to hook the reader (Bang!, surprise fact, dialogue), includes some character and setting details.  Persuasive text: includes a hook, background/context on the topic and a thesis statement. Information text: Opening sentence and description of topic.');
insert into global_criterias(description) values ('	Write using joined letters that are clearly formed and consistent in size.   Practising how to join letters to construct a fluent handwriting style.');
insert into global_criterias(description) values ('	The topic is narrow and focused on the main idea.');
insert into global_criterias(description) values ('	Understands that paragraphs are a key organisational feature of written texts.  Understands and there is evidence of attempts to paragraph when the topic, speaker, place or time changes.');
insert into global_criterias(description) values ('	Relevant and quality details support ideas within texts.');
insert into global_criterias(description) values ('	Identifies important ideas within a text and adds relevant detail using precise nouns, verbs, adjectives and strategies such as "show don''t tell."');
insert into global_criterias(description) values ('	Varied sentence length is used to enhance fluency and readability.');
insert into global_criterias(description) values ('	Can manipulate the pace by using strategies such as "Show don''t Tell" or increasing descriptive detail for important events within a narrative or recount.');
insert into global_criterias(description) values ('	Uses full stops, capitals, question marks, commas and exclamation marks (80%+ accuracy).  Experimenting with other punctuation (''... "").');
insert into global_criterias(description) values ('	Uses connectives to link ideas (and, because), signal a shift in time or setting (later on) and contrast ideas (although, yet).	');
insert into global_criterias(description) values ('	Is experimenting with a range of linking devices to make texts more cohesive, including pronouns, connectives, synonyms and word associations (e.g. words that refer to the main character).');
insert into global_criterias(description) values ('	Can plan, draft and publish imaginative, informative and persuasive texts demonstrating increasing control over text structures and language features.');
insert into global_criterias(description) values ('	Sentences beginnings are varied. Experimenting with  different beginnings to make writing interesting, including prepositional phrases, a range of transitions, proper nouns, verbs, adjectives and subordinating conjunctions.	');
insert into global_criterias(description) values ('	Sentences have subject verb agreement.  Correct and appropriate (informal contexts) use of word contractions.  Exploring a range of verbs (action, thinking, sensing).  Can use apostrophe to show possession for singular nouns (the cat''s toy).');
insert into global_criterias(description) values ('	Uses precise and accurate words throughout text to create strong mental images and enhance meaning, including some topic specific vocabulary.  For example, "teammates", instead of "other players".');
insert into global_criterias(description) values ('	Use software including word processing programs with growing speed and efficiency to plan, sequence, compose and edit texts featuring visual, print and audio elements. Familiar with hyperlinks, navigation bars and buttons.');
insert into global_criterias(description) values ('	Can create a summary for events/experiences and familiar fictional texts, including relevant information on characters, setting, conflicts and resolutions.  Can skim non-fiction texts and note key points or main ideas.');
insert into global_criterias(description) values ('	Consistent use of precise, modal, and technical (habitat) content words to express opinion and enhance meaning.  Experimenting with some ambitious adjectives, adverbs and phrases.');
insert into global_criterias(description) values ('	Can create complex sentences using subordinating conjunctions. For example, "After the game, we celebrated with a team dinner".	');
insert into global_criterias(description) values ('	Chooses appropriate text types and language features to suit both audience and purpose.');
insert into global_criterias(description) values ('	Variation in sentence length and sentence beginnings enhances flow and fluency in parts of the text.');
insert into global_criterias(description) values ('	Uses language features and organisational patterns to support texts. For example, writes numbered steps for a procedural text and begins each step with a verb.');
insert into global_criterias(description) values ('	The writer is clearly engaged in the topic and developing a strong voice.  For example, may use interjections to reflect a feeling or their opinion (Yay!, Finally!).');
insert into global_criterias(description) values ('	Can spell most unknown polysyllabic words using strategies and patterns: diphthongs (ai, oy), single syllable homophones (ate/eight), plural (-s,-es), and past tense (-ed).');
insert into global_criterias(description) values ('	For imaginative texts, has a satisfying ending appropriate for audience and purpose. Persuasive text concludes by restating the main contention and  summarising key arguments with a call to action.');
insert into global_criterias(description) values ('	Uses a range of common figurative language (similes, metaphors, hyperbole, alliteration, personification).  Is experimenting with oxymorons (It was seriously funny, we have a love-hate relationship).');
insert into global_criterias(description) values ('	Confidently finds interesting and original ideas from a range of sources  (visual prompts, personal experience, observations, texts, inspiration from historical person/event).');
insert into global_criterias(description) values ('	Revises and edits text to improve ideas, meaning, word choice and text structure to fit audience and purpose.');
insert into global_criterias(description) values ('	Characters are made memorable through descriptive and relevant detail (noun/adjective phrases) that contribute to the sequence of events ("Her stomach tightened as she walked on stage.").');
insert into global_criterias(description) values ('	Narrative: Engaging orientation with a hook, character and setting details.  Persuasive text: includes a hook, background/context on the topic and a thesis statement. Information text: Includes a hook and description of topic.');
insert into global_criterias(description) values ('	Handwriting is neat using clearly-formed joined letters.  Is developing increased fluency with speed and automaticity for a wide range of tasks.');
insert into global_criterias(description) values ('	The topic is interesting and focused on the main idea.');
insert into global_criterias(description) values ('	Can organise text using paragraphs when the topic, speaker, time or location changes.  For information texts, some evidence of organising longer texts with topic sentences and supporting details.');
insert into global_criterias(description) values ('	Ideas are supported and enriched using noun groups/phrases, verb groups/phrases and prepositional phrases. For example: Narrative texts, "their very friendly neigbour, who always says hello"; in reports, "At sunrise, during low tide, you can walk to the island."');
insert into global_criterias(description) values ('	Ideas are supported and enriched using noun groups/phrases, adjectives and prepositional phrases. For example, "All through the night, the scared dog barked."');
insert into global_criterias(description) values ('	Varied sentence length is used thoughtfully to enhance fluency and for effect.  For example, the writer creatively uses interjections or short two word phrases.');
insert into global_criterias(description) values ('	Writes with more detail during climatic plot points to build tension.  Uses strategies such as "Show don''t Tell" and descriptive detail to slow down the pace and focus on important events.');
insert into global_criterias(description) values ('	Uses full stops, commas, exclamation and question marks accurately. Can use other punctuation (''... "":) accurately.');
insert into global_criterias(description) values ('	Uses common and some sophisticated connectives appropriate to purpose in text (however, therefore, in addition, in summary).');
insert into global_criterias(description) values ('	Makes cohesive links throughout the text using linking devices, including pronouns (he, she, this, that, the, those, these), text connectives, word associations.');
insert into global_criterias(description) values ('	Can create imaginative, informative and persuasive texts with increasing control over structure, language features, storylines, characters and settings.  Creates texts that explore students’ own experiences.');
insert into global_criterias(description) values ('	Thoughtful, varied sentence beginnings signal to the reader how the text is developing.  Includes prepositional phrases, a range of transitions, proper nouns, verbs, adjectives and subordinating conjunctions.');
insert into global_criterias(description) values ('	Uses nouns, pronouns, plurals, tenses consistently and accurately throughout texts.  Uses adverbs and verbs to represent different processes with correct tense (He curiously smiled).');
insert into global_criterias(description) values ('	Uses precise and accurate words throughout text to create strong mental images and enhance meaning.  With support, can reword a sentence to make it more concise (less wordy) without sacrificing meaning.');
insert into global_criterias(description) values ('	Can select from a range of appropriate software to construct, edit and publish written text, and select, edit and include visual, print and audio elements.  Can discuss differences between print and digital information. Can touch type 20-30 wpm.');
insert into global_criterias(description) values ('	Can write a concise summary with relevant information for events/experiences and fictional texts.  Can skim non-fiction texts and note key points or main ideas, omitting small details.');
insert into global_criterias(description) values ('	Uses expressive verbs (transformed, pleaded) and less predictable imaginative and technical words and phrases, drawn from a range of sources (thesaurus, own research, imitating similar texts).');
insert into global_criterias(description) values ('	Creates richer and more specific descriptions using prepositional, noun and verb groups/phrases.  Uses a range of simple, compound and complex sentences to express ideas.');
insert into global_criterias(description) values ('	The author has considered point of view (first/third person), topic, text structure and language features to support the intended audience and purpose.');
insert into global_criterias(description) values ('	Sentences flow smoothly, and do not feel choppy.  The text is easy and enjoyable to read aloud.');
insert into global_criterias(description) values ('	Experimenting with the use of quotation marks to signal dialogue, titles and quoted (direct) speech. Language features and organisational patterns support texts.');
insert into global_criterias(description) values ('	The author''s voice is clearly evident throughout the text through careful word choice and other devices like: rhetorical questions, inverted commas, exclamation marks, interjections, sarcasm.');
insert into global_criterias(description) values ('	Uses phonic and visual knowledge and spelling patterns to spell unfamiliar words. May use syllabification, letter combinations, double letters, word families, silent beginning patterns ("kn" and "gn").');
insert into global_criterias(description) values ('	Satisfying conclusion using appropriate language and text features for purpose and audience. Experiments with different endings (a twist, implied, unresolved or circular ending).');
insert into global_criterias(description) values ('	Creatively uses a range of figurative language to fit purpose and audience.  Hyperbole and sarcasm in persuasive texts, and  personification for poetry.');
insert into global_criterias(description) values ('	Revises and edits own and others'' text using agreed criteria to improve organisation of ideas, meaning, word choice, sentence fluency and text structure.');
insert into global_criterias(description) values ('	Characters have depth and personality. Their intentions and motivations drive the piece and the author has made attempts to help the reader form an emotional connection with the protagonist.');
insert into global_criterias(description) values ('	Experimenting with or imitating different openings to develop a strong narrative and/or persuasive voice.  E.g. "I hid under my blankets, as water pelted the old tin roof and the sky lit up like a firecracker."');
insert into global_criterias(description) values ('	Can identify degrees of modality in texts.  Example: I will get up early. (high modality). I might get up early. (low modality).');
insert into global_criterias(description) values ('	Developing a handwriting style that is becoming legible, fluent and automatic.');
insert into global_criterias(description) values ('	Can organise texts using paragraphs when the topic, speaker, time or location changes. For information texts, organises longer texts with topic sentences and supporting details.');
insert into global_criterias(description) values ('	Person, place, thing or idea within various text types is supported and enriched using adjectives, prepositions, and noun and verb groups/phrases.  For example: Narrative texts, "Their very friendly neighbour, who always says hello, gave them the cold shoulder"; in reports, "At sunrise, during low tide, you can walk to the island."');
insert into global_criterias(description) values ('	Varied sentence length is used thoughtfully for different text types to support meaning, for fluency and effect.  For example, in a procedural text, the writer uses short, concise sentences.');
insert into global_criterias(description) values ('	Pacing is generally controlled, with the author showing attempts to provide different amounts of information and level of detail to speed up or slow down events.');
insert into global_criterias(description) values ('	"Uses a range of punctuation accurately to support meaning. (, . ? ! '' "" "" : ...)"	');
insert into global_criterias(description) values ('	Effectively uses a range of connectives to compare and contrast (similarly, by contrast), elaborate (additionally) and conclude (to sum up).');
insert into global_criterias(description) values ('	Makes cohesive links within and between sentences using a range of pronouns (he, she, this, that, the, those, these) text connectives and synonyms to avoid repetition and improve flow.');
insert into global_criterias(description) values ('	Can plan, draft and publish imaginative, informative and persuasive texts and create texts using realistic and fantasy settings and characters that draw on worlds represented in texts students have experienced.');
insert into global_criterias(description) values ('	A range of thoughtful and interesting sentence beginnings gives prominence to the message, links ideas smoothly and allows for prediction of how the text will unfold. See ELABORATION for examples.');
insert into global_criterias(description) values ('	Correct use of apostrophe for plural nouns (my parents'' care) and to show possession for singular nouns (my mother''s cat).');
insert into global_criterias(description) values ('	Precise language is used to create greater precision and avoid wordiness. The author''s message is clear and easy to understand. For example, instead of "cut", uses "shred", "slice", "dice".');
insert into global_criterias(description) values ('	Use a range of software including word processing programs to construct, edit and publish written text, and select, edit and place visual, print and audio elements. Can write and send emails. Can touch type 30-40 wpm.');
insert into global_criterias(description) values ('	Can represent the main ideas of any text or event/experience in a short written summary using concise language. For example, substitutes "oak, pine, gum and maple trees" with "trees".	');
insert into global_criterias(description) values ('	Experimenting with vocabulary choices, including evaluative language to expresses greater precision of meaning and effect. (She was the "most" "frightful" person I had met).');
insert into global_criterias(description) values ('	Uses complex sentences to make connections between ideas.  Understands the difference between main and subordinate clauses.	');
insert into global_criterias(description) values ('	Variation in sentence length, structure and word choice creates a pleasing and natural rhythm and cadence.');
insert into global_criterias(description) values ('	Appropriate use of quotation marks to signal dialogue, titles and quoted (direct) speech. Language features and organisational patterns support texts.');
insert into global_criterias(description) values ('	Adapts the right tone (humorous, sarcastic, assertive, informative) to suit the topic, audience and purpose.  Confident and appropriate language draws the reader in.');
insert into global_criterias(description) values ('	Recognise and write less familiar words that share common letter patterns but have different pronunciations.  For example, the "ou" in "journey", "your", "tour", "sour".');
insert into global_criterias(description) values ('	Satisfying ending using sophisticated language and text features for purpose and audience.');
insert into global_criterias(description) values ('	Creatively uses figurative language to fit purpose and audience. Experimenting with idioms, irony (sarcasm) and allusion.');
insert into global_criterias(description) values ('	Revises and edits own and others'' work using agreed criteria. Makes changes appropriate to task and audience: cohesion, sequencing, vocabulary and a range of literary devices (humour, pathos).');
insert into global_criterias(description) values ('	Direct (telling) and indirect  (show don''t tell) characterisation techniques describe character traits, giving them depth and personality. Literary devices (flashbacks and foreshadowing) reveal their intentions and motivations.');
insert into global_criterias(description) values ('	Writes a strong opening with an understanding of audience and purpose. Creatively uses imagery to to describe setting. Has a strong voice that sets the mood and tone of the piece.');
insert into global_criterias(description) values ('	Expresses a stronger point of view through choices of modal verbs, adverbs, adjectives or nouns. For example: "We must care for elderly citizens", uses a high modality verb "must".');
insert into global_criterias(description) values ('	Develop a handwriting style that is legible, fluent and that can vary depending on audience and purpose, including word processing programs to create texts.');
insert into global_criterias(description) values ('	Compare texts including media texts (news reports) that represent ideas and events in different ways, and explaining the effects of the different approaches.  For example, comparing advertisements from two different countries.');
insert into global_criterias(description) values ('	Can organise texts using paragraphs when the topic, speaker, time or location changes. For information texts, organises longer texts with topic sentences, elaborations and some closing sentences.');
insert into global_criterias(description) values ('	Ideas for various text types are expanded and enriched through careful choice of precise verbs.  Uses a range of prepositional and adverb, noun, and verb group/phrases with correct tense. For example, "In the morning, around 10am, I began training for the race." Uses conjunctions in complex sentences to extend ideas.');
insert into global_criterias(description) values ('	Pacing is controlled throughout the whole piece, with the author giving the right amount of information and level of detail to speed up or slow down events to hold the reader''s attention.');
insert into global_criterias(description) values ('	Uses a range of punctuation accurately. (, . ? ! '' "" "" : ...) Can use commas to separate a list and clauses in a sentence.');
insert into global_criterias(description) values ('	Some sophisticated connective phrases link ideas and enhance fluency (for this reason, equally important, on the whole).');
insert into global_criterias(description) values ('	Can use a range of devices that aid cohesion including pronouns, connectives, synonyms, antonyms, juxtaposition, substituting a specific word for a general one already mentioned (Borneo and Island).');
insert into global_criterias(description) values ('	Can plan, draft and publish imaginative, informative and persuasive texts, choosing and experimenting with text structures, language features, images and digital resources appropriate to purpose and audience.');
insert into global_criterias(description) values ('	Consistent and accurate use of apostrophes (plural and singular nouns) prefixes, pronouns, suffixes, compound words. All sentences have subject verb agreement with correct tense.');
insert into global_criterias(description) values ('	Sophisticated precise and accurate topic specific  vocabulary is used to create greater precision and avoid wordiness.  For example, instead of "front" of the boat, the author writes "bow" of the boat.  Effectively uses an active voice for information texts.');
insert into global_criterias(description) values ('	Confidently uses and explores a range of software, including word processing programs, learning new functions as required to create texts.  For example, may use CANVA to create a flyer.');
insert into global_criterias(description) values ('	Refined and appropriate vocabulary choices, including evaluative language, express shades of meaning, feeling and opinion ("Protesters stormed", "Peaceful protesters approached").');
insert into global_criterias(description) values ('	Uses complex sentences in a variety of ways to elaborate, extend and explain ideas. See VCELA350 ELABORATION for examples.');
insert into global_criterias(description) values ('	Sentence structure, word choice and at least one literary device (alliteration, consonance, repetition, rhyme) add to the overall fluency of the piece and invites expressive reading.');
insert into global_criterias(description) values ('	Can use a range of text structures and language features to support texts. For example, emotive language in persuasive texts, graph, table, and diagram for visual representations, sensory language to covey vivid pictures.');
insert into global_criterias(description) values ('	The author''s attitude towards the topic and their distinct personality is evident. Engages and involves the reader using higher order devices such as word play and innuendo ("if you know what I mean").');
insert into global_criterias(description) values ('	Can spell increasingly complex words using word origins, base words, prefixes, suffixes, spelling patterns, including technical words.');
insert into global_criterias(description) values ('	Satisfying and strong ending for purpose and audience.  Final sentences (thoughts) evoke inspiration, realisations or insights that linger in the reader''s mind.');
insert into global_criterias(description) values ('	Uses figurative language where fit, without overusing or sounding cliche.  Creatively engages readers using idioms, irony (sarcasm) and allusion (can be within a simile or metaphor).');
insert into global_criterias(description) values ('	Edits for meaning by removing repetition (concise), refining ideas, reordering sentences and adding or substituting words for impact.  Uses collaborative technologies to jointly construct and edit texts.');
insert into global_criterias(description) values ('	Characters are developed  through a variety of techniques: narration, dialogue, thoughts, and their interaction with other characters and the setting.');
insert into global_criterias(description) values ('	Writes a strong opening, with an understanding of audience and purpose.  Thoughtful word choice, using a strong voice that sets the mood and tone.  Appeals to emotion (pathos), logic (logos) and/or ethics (ethos) in persuasive introduction.');
insert into global_criterias(description) values ('	Expresses certainty in texts through choices of modal verbs, adverbs, adjectives and nouns. For example: "Regular exercise will improve your health", achieves certainty using the high modality verb "will".	');
insert into global_criterias(description) values ('	Consolidate a personal handwriting style that is legible, fluent and automatic and supports writing for extended periods.');
insert into global_criterias(description) values ('	Organises a variety of texts with well structured paragraphs, including initial and concluding paragraphs to create cohesion of ideas presented with a text.');
insert into global_criterias(description) values ('	Creatively controls the pace using just the right amount of detail and using one or more of the following: sentence length, shifting the focus to subplots, or time transitions.  The piece feels balanced.');
insert into global_criterias(description) values ('	Uses punctuation correctly to support meaning in texts for different sentence structures (complex, prepositional phrases, embedded clauses).');
insert into global_criterias(description) values ('	Connective words/phrases smoothly link ideas to compare and contrast (similarly, by contrast), elaborate (in particular), give examples (take for instance) and conclude (on the whole).');
insert into global_criterias(description) values ('	Complex texts are made coherent through cohesive devices (pronouns, connectives, synonyms) and text structure to guide readers.  For example, overviews, initial and concluding paragraphs, indexes, topic sentences.');
insert into global_criterias(description) values ('	Plan, draft and publish a range of texts, selecting subject matter, language, visual, and audio features to convey information and ideas to a specific audience.');
insert into global_criterias(description) values ('	Uses a range of software to create, edit and publish written and multimodal texts. Understands different conventions of software and can synthesise information in dot points, sequence information in presentations and time scenes in an animation.');
insert into global_criterias(description) values ('	Creatively uses a range of clause types to express, extend and develop ideas.');
insert into global_criterias(description) values ('	Well crafted sentences, intentional fragments, comma usage and stylistic features (adapted from similar texts) enhance readability and fluency.');
insert into global_criterias(description) values ('	Adapting a range of higher order stylistic features encountered in literary texts (flashbacks, multiple perspectives).  See ELABORATION for more examples.');
insert into global_criterias(description) values ('	Confidently uses a range of "voice" techniques to create effect and involve the reader.  The writer is developing a unique style that avoids cliches.');
insert into global_criterias(description) values ('	Uses spelling rules and patterns, word origins (Greek, Latin roots) to accurately spell new words. Can spell some common words from other languages (bon voyage, entree).');
